---
- name: Install Gitlab
  hosts: gitlab.com
  gather_facts: true
  become: true
  
  tasks:
    - name: install dependencies
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
        - curl
        - openssh-server
        - ca-certificates

    - name: Add gitlabe repository to the repository list
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
      args:
        executable: /bin/bash

    - name: Install gitlab package
      apt: 
        update_cache: yes
        name: gitlab-ce
